name       : perl-json
version    : 2.91.04
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/I/IS/ISHIGAKI/JSON-2.91_04.tar.gz : df2fd1a7361cc291d01198382aa19153a6010ee037a0c7a7eaec73e401908ce7
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : JSON (JavaScript Object Notation) encoder/decoder
description: |
    JSON (JavaScript Object Notation) encoder/decoder
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
