name       : perl-json
version    : '2.96'
release    : 2
source     :
    - https://www.cpan.org/authors/id/I/IS/ISHIGAKI/JSON-2.96.tar.gz : e4b1d7461e99ab26e548e6bf87e7a785b99d5ec6425b66b163fba34b7450526a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : JSON (JavaScript Object Notation) encoder/decoder
description: |
    JSON (JavaScript Object Notation) encoder/decoder
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
