name       : perl-json
version    : '4.02'
release    : 5
source     :
    - https://www.cpan.org/authors/id/I/IS/ISHIGAKI/JSON-4.02.tar.gz : 444a88755a89ffa2a5424ab4ed1d11dca61808ebef57e81243424619a9e8627c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : JSON (JavaScript Object Notation) encoder/decoder
description: |
    JSON (JavaScript Object Notation) encoder/decoder
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
