name       : perl-json
version    : '4.09'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/JSON-4.09.tar.gz : 6780a51f438c0932eec0534fc9cd2b1ad0d64817eda4add8ede5ec77d6d2c991
homepage   : https://metacpan.org/pod/JSON
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : JSON (JavaScript Object Notation) encoder/decoder
description: |
    This module is a thin wrapper for JSON::XS-compatible modules with a few additional features. All the backend modules convert a Perl data structure to a JSON text and vice versa. This module uses JSON::XS by default, and when JSON::XS is not available, falls back on JSON::PP, which is in the Perl core since 5.14. If JSON::PP is not available either, this module then falls back on JSON::backportPP (which is actually JSON::PP in a different .pm file) bundled in the same distribution as this module. You can also explicitly specify to use Cpanel::JSON::XS, a fork of JSON::XS by Reini Urban.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
